export const LOAD_DATA = 'LOAD_DATA'
export const CHANGE_SWITCH = 'CHANGE_SWITCH'
export const VALUE_CHANGE = 'VALUE_CHANGE'
export const CHOOSE_DATE = 'CHOOSE_DATE'
export const SAVE_PLAN = 'SAVE_PLAN'